# .streamlit/config.toml

[theme]
# Core Colors
primaryColor="#4A4A4A"  # Dark Gray for interactive elements
backgroundColor="#F0F2F6" # Light Gray background
secondaryBackgroundColor="#FFFFFF" # White for cards/containers/expander background
textColor="#31333F" # Dark Gray/Near Black for text

# Font
font="sans serif"

[mapbox]
# Mapbox style (not used, but part of theme)
style = "light"